server:
  port: 8094

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: ledgers
  resource: ledgers-client
  public-client: false
  principal-attribute: preferred_username
  credentials:
    secret: a61a81cd-7178-40d8-8386-ed02791e6592 #Here should be personal generated secret for client (swap public to 'private?' generate secret, swap to public again)

springdoc:
  api-docs:
    enabled: false

spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase-master-changelog.xml
    default-schema: tpp
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 2MB
  jackson:
    serialization:
      write_dates_as_timestamps: false
  devtools:
    remote:
      secret: fractal

spring.datasource.hikari.jdbc-url: jdbc:postgresql://localhost:5432/consent?currentSchema=consent
spring.datasource.hikari.username: cms
spring.datasource.hikari.password: cms

ledgers.url: http://localhost:8088

license.url: https://github.com/adorsys/xs2a/blob/master/LICENSE.md

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full

logging.level.de.adorsys.psd2.sandbox.admin: INFO

logging.level.de.adorsys.ledgers.middleware.client.rest.AdminRestClient: DEBUG

# Cors configuration
management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-origins: "*"
        allowed-headers: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
        max-age: 3600
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  health:
    mail:
      enabled: false

app:
  endpoints:
    admin.self.registration.disabled: false
